# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoRevisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crev', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='rev_id',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='rev_num',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='ToDo date'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.TodoRevisions'),
        ),
    ]
