# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-15 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160913_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='name',
            new_name='status',
        ),
    ]
